---
title: "htmlwidgets"
output:
  slidy_presentation:
    theme: default
css: "www/teachingnotes.css"
runtime: shiny
---

## htmlwidgets: JavaScript

The interactive web is driven by JavaScript*.

The majority of interactive elements that you use on websites are written in JavaScript - from interactive maps to auto-completing pop-up menus. 

```{r, echo=F}
library(shiny)
library(leaflet)
shinyApp(
  ui = fluidPage(
    sidebarLayout(
      sidebarPanel(
    sliderInput("latitutde", label = "Latitude", min = 5, max = 8, value = 6.9),
    sliderInput("longitude", label = "Longtidue", min = 15, max = 19, value = 17.7),
    sliderInput("sd", label = "Standard Deviation of Points", min = 5, max = 20, value = 10),
    selectInput("mapType", label = "Map Type:", choices = c("OpenStreetMap", "OpenStreetMap.BlackAndWhite","OpenTopoMap"))),
    mainPanel(
    leafletOutput("africa_map")
  ))),
  server = function(input, output) {
    
    output$africa_map <- renderLeaflet({
      
      africa_data_points = data.frame(
      lat = rnorm(100, mean = input$latitutde, sd = input$sd),
      lng = rnorm(100, mean = input$longitude, sd = input$sd),
      size = runif(100, 5, 10),
      popup = as.character(1:100)
    )
    
      m <- leaflet(africa_data_points) %>%
        addProviderTiles(input$mapType)
      m %>% addCircleMarkers(radius = ~size, popup = ~popup)
      
    })
  },options = list(height = "100%")
)

```

## htmlwidgets: The Framework

Like in R, there are hundreds of different JavaScript libraries dedicated to various visualisation tasks. 

There is a package called `htmlwidgets` that allows R developers to easily build bindings to JavaScript libraries, allowing incredibly rich interactive content for the web to be built using just the R language.

## htmlwidgets: The Packages

These bindings to JavaScript libraries are typically distributed as individual R packages

- An individual R package for an individual JavaScript library. 


The <a href="http://htmlwidgets.org">htmlwidgets.org</a> website provides a showcase of some of the `htmlwidget` dependent bindings that are available through CRAN.

## Which libraries will we cover?

We're going to cover the basis of these four libraries:

>- leaflet: the *best* tool for creating complex maps (see mapview for a simpler but less versatile tool)
>- plotly: an excellent tool for charting, plotting and statistical visualisations (includes the ability to convert static ggplot2 charts into interactive visualisations)
>- highcharter: a beautiful tool for charting and plotting data, which is not free for commerical or Governmental use
>- datatable: an excellent tool for creating interactive tables

## How different to one another are these tools?

I've specifically chosen this set up htmlwidgets because they're each very useful, but are quite different from one another in how they're used.

We'll run through the basics of each tool and there are a number of exercises as well.

